### ISSUE TITLE
Filter Types In RAML Export

### ISSUE THREAD

**Issue by ranacseruet** [stoplightio/api-spec-converter#1]
RAML has some restricted list of supported types for parameters(https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#type). However, stoplight has some support for additional parameter types, for example: array.

Need to figure out how to map those params in exported RAML. ATM, such incompatible types can cause error in importing those exported raml.

**Comment by marbemac** [comment]
Wow, they don't support arrays in request bodies?

On Tue, Nov 24, 2015 at 3:26 PM, Rana Md Ali Ahsan <notifications@github.com

**Comment by ranacseruet** [comment]
It will be OK if the request body is a json schema, as the raml parser treats the schema as string. But if its form param and specified detailed in its own format, then yes, its not accepting that. Same for query string params as well. I wanted to open a ticket there to see what they have in mind, but seems like they have something similar already reported: https://github.com/raml-org/raml-spec/issues/152
