### ISSUE TITLE
Try Out New Beta raml-parser-2 

### ISSUE THREAD

**Issue by ranacseruet** [stoplightio/api-spec-converter#3]
Whether the library is not very much buggy or not and to check if we can support RAML 1.0 decently.

Library's Github URL: https://github.com/raml-org/raml-js-parser-2

**Comment by llattes** [comment]
Any update on this? The parser seems pretty stable lately, are you planning including this?
Is there any roadmap or high-level plans for `api-spec-converter`? 
See https://github.com/raml-org/raml-js-parser-2 for details.

**Comment by glodieu** [comment]
issue fixed in raml10 branch.
