### ISSUE TITLE
Release version 0.2.6 not available https://github.com/stoplightio/api-spec-converter/releases

### ISSUE THREAD

**Issue by MariaClemence** [stoplightio/api-spec-converter#46]
I am not able to find released version for 0.2.6 in https://github.com/stoplightio/api-spec-converter/releases, however we see the same version available in npm.

**Comment by Karthik-M-L** [comment]
+1

**Comment by Karthik-M-L** [comment]
This is confusing, everywhere latest version 0.2.6 but in releases it shows latest version is 0.1.16. Could you please check and update in the releases.

**Comment by marbemac** [comment]
Hi guys, we will build and put the zip in the releases list. However, note that if this is urgent you can always do an "npm i api-spec-transformer" and then take the folder that is added. Or you can clone this repository and just run the build command to get the built release.

That said, will get the release on that list soon :).

**Comment by marbemac** [comment]
In fact, I forgot. If you look at the release zip, it's just the repository files zipped... so you guys can download the repository code and it's the same thing.

**Comment by MariaClemence** [comment]
Hi Marc, Thanks for the updates. In case i need the source code for for different versions i would could get the same from the tagged releases (Current latest tagged release is 0.1.16) and i am also expecting to see 0.2.6 in tagged released as it is already released.

I master branch is see 0.2.6 as well. should'nt this be pointing to the next version of the software?
