### ISSUE TITLE
Interpreting 'default' response code

### ISSUE THREAD

**Issue by ranacseruet** [stoplightio/api-spec-converter#5]
Check [this section on swagger spec](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#responses-object). Besides all other valid http status code, swagger also has concept of 'default' code, which represents all codes which aren't presented in the spec.

At this moment, this code is converted to '400' http code, when imported. But it has two potential problems:

1. There could be another response definition with code '400' . So, only one of these will get imported finally.
2. It isn't representing all codes, which aren't covered, which originally meant by swagger spec.

@marbemac , I would like to hear about your thoughts on this. 

(May be not anything urgent as on import functionality)

**Comment by marbemac** [comment]
add it as 'default' - i'm going to support this in the designer / prism.

https://www.pivotaltracker.com/story/show/113176423

**Comment by ranacseruet** [comment]
I have committed the changes. After you making the changes in dashboard/prism, please let me know so that I can test or verify from your side.
