### ISSUE TITLE
Tags And External Docs Support

### ISSUE THREAD

**Issue by ranacseruet** [stoplightio/api-spec-converter#8]
We don't have support for thiis two attributes in the rool level swagger spec definition:

- tags
- externalDocs

**Comment by ranacseruet** [comment]
@marbemac , we probably can consider adding 'externalDocs' support after public documentation feature is completely ready, by putting the url of public docs(where applicable) on this field, while exporting.

**Comment by glodieu** [comment]
issue fixed in raml10 branch.
